### PR TITLE
Move gantt-chart out from subdirectory

### PR DESCRIPTION
**Pull request by joshuali925**
### Description
Currently all frontend plugins are under git root except gantt-chart, this PR makes the directory structure more consistent with other plugins.

This PR is a prerequisite for https://github.com/opensearch-project/opensearch-build/pull/4375, which will do the corresponding change in the build repo

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]
LGTM

**Comment by derek-ho** [comment]
Do you want to backport this for 2.12 release?

**Comment by joshuali925** [comment]
> Do you want to backport this for 2.12 release?

yes but doesn't need to be in 2.12, since it doesn't make a difference for users

**Review by mengweieric — COMMENTED** [review]
Looks good

**Review by mengweieric — APPROVED** [review]

**Comment by vamsi-amazon** [comment]
Looks good. Thanks.

**Pull request merged**
